
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'A B NLstmt : S NLS : A S BS : '
    
_lr_action_items = {'A':([0,3,],[3,3,]),'NL':([0,2,6,],[-3,4,-2,]),'$end':([1,4,],[0,-1,]),'B':([3,5,6,],[-3,6,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'stmt':([0,],[1,]),'S':([0,3,],[2,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> stmt","S'",1,None,None,None),
  ('stmt -> S NL','stmt',2,'p_stmt','Exp4_LL1Parser.py',24),
  ('S -> A S B','S',3,'p_S_rec','Exp4_LL1Parser.py',28),
  ('S -> <empty>','S',0,'p_S_empty','Exp4_LL1Parser.py',32),
]
